apiVersion: v1
kind: Secret
metadata:
  name: example-voting-app
  labels:
    name: example-voting-app
    app: example-voting-app
  namespace: lab2-example-voting-app
type: Opaque
data:
  db_url: '[REDACTED]='
  redis_url: '[REDACTED]'
  jdbc_db_url: '[REDACTED]'
