global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
- job_name: nginx-prod
  static_configs:
  - targets: ['localhost:9113']
- job_name: nginx-dev
  static_configs:
  - targets: ['localhost:9114']
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']
  
