dev_new_k8s: true
k8s_cluster_name: sysdig-training
snaplen: 512
collector: collector-staging3.sysdigcloud.com
collector_port: 6443
ssl: true
ssl_verify_certificate: false
security:
    enabled: true
    k8s_audit_server_url: 0.0.0.0
    k8s_audit_server_port: 7765
prometheus:
  enabled: true
  interval: 10
  log_errors: true
  max_metrics: 10000
  max_metrics_per_process: 2000
  max_tags_per_metric: 5000
  # histograms: true
  process_filter:
    - include:
        process.name: grok_exporter
        conf:
          host: localhost
          port: 9144
          path: '/metrics'
app_checks:
  - name: ntp
    check_module: ntp
    pattern:
      comm: ntpd
  - name: mysql
    pattern:
      comm: mysqld
    conf:
      server: 127.0.0.1
      user: sysdig-cloud
      pass: sysdig-cloud-password

percentiles: [50, 95, 99]
