version: "3.1"
services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  postgres-exporter:
    image: wrouesnel/postgres_exporter:v0.8.0
    restart: always
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:[REDACTED]@postgres-db:5432/postgres?sslmode=disable
      - DATA_SOURCE_URI=postgres-db:5432/postgres?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=password
    ports:
      - "9187:9187"
    labels:
        - "io.prometheus.scrape=true"    
        - "io.prometheus.port=9187"
    depends_on:
      - postgres-db

